# Generated by Django 4.2.1 on 2023-06-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_semestermarks_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semestermarks',
            options={'verbose_name': 'Оценки', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AddField(
            model_name='semestermarks',
            name='diplom',
            field=models.BooleanField(default=False, verbose_name='Оценка идёт в диплом'),
        ),
        migrations.AlterUniqueTogether(
            name='semestermarks',
            unique_together={('subject', 'student')},
        ),
    ]
