# Generated by Django 4.2.1 on 2023-06-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_semestermarks_options_semestermarks_diplom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='otdel',
            field=models.CharField(choices=[('OC', 'Очное'), ('ZA', 'Заочное')], max_length=2, null=True, verbose_name='Отделение'),
        ),
        migrations.AddField(
            model_name='studenttogroup',
            name='zachotka',
            field=models.CharField(db_index=True, max_length=20, null=True, verbose_name='Номер зачётки'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(blank=True, db_index=True, default=None, null=True, verbose_name='Дата проведения занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='independentTask',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Задание для работы в классе'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.CharField(default='', max_length=125, null=True, verbose_name='Тема занятия'),
        ),
    ]
