# Generated by Django 4.2.1 on 2023-06-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_groups_otdel_studenttogroup_zachotka_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='hours',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=300, null=True, verbose_name='Адрес проживания'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='num',
            field=models.CharField(max_length=11, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='subjecttoteacher',
            name='course',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='subjecttoteacher',
            name='hours',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество часов'),
        ),
    ]
