# Generated by Django 4.2.1 on 2023-06-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_remove_subject_hours_customuser_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestermarks',
            name='diplom',
        ),
        migrations.RemoveField(
            model_name='semestermarks',
            name='type',
        ),
        migrations.AddField(
            model_name='subjecttoteacher',
            name='diplom',
            field=models.BooleanField(default=False, verbose_name='Оценка идёт в диплом'),
        ),
        migrations.AddField(
            model_name='subjecttoteacher',
            name='type',
            field=models.CharField(choices=[('EX', 'Экзамен'), ('ZA', 'Зачёт'), ('DZ', 'Диффиринцированный зачёт'), ('OT', 'Иные формы контроля')], default='OT', max_length=2, verbose_name='Форма аттестации'),
        ),
    ]
