# Generated by Django 4.2.1 on 2023-06-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_remove_semestermarks_diplom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semestermarks',
            options={'verbose_name': 'Оценки за семестр', 'verbose_name_plural': 'Оценки за семестр'},
        ),
        migrations.AlterUniqueTogether(
            name='semestermarks',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.CharField(max_length=10, null=True, verbose_name='Тип занятия'),
        ),
        migrations.AddField(
            model_name='semestermarks',
            name='type',
            field=models.CharField(choices=[('SE', 'Семестр'), ('DI', 'Диплом')], default='SE', max_length=2, verbose_name='Тип оценки'),
        ),
    ]
