# Generated by Django 4.2.1 on 2023-06-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_semestermarks_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttogroup',
            name='health',
            field=models.CharField(choices=[('MA', 'Основная'), ('SP', 'Специальная'), ('PO', 'Подготовительная')], default='MA', max_length=2, verbose_name='Группа по физкультуре'),
        ),
    ]
