# Generated by Django 4.2.1 on 2023-06-05 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_studenttogroup_health'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SemestrInfo',
        ),
    ]
