# Generated by Django 4.2.1 on 2023-06-05 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_remove_subject_type_alter_groups_start_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('IT', 'Программист'), ('TE', 'Преподаватель'), ('ST', 'Студент'), ('AD', 'Администрация')], default='ST', max_length=2, null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='subjecttoteacher',
            name='semestr',
            field=models.PositiveIntegerField(db_index=True, default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)], verbose_name='Семестр'),
        ),
    ]
