# Generated by Django 4.2.1 on 2023-06-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_semestrinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SemestrInfo',
            new_name='SemesterInfo',
        ),
        migrations.RenameField(
            model_name='semesterinfo',
            old_name='semestr',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='subjecttoteacher',
            old_name='semestr',
            new_name='semester',
        ),
    ]
