# Generated by Django 4.2.1 on 2023-06-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_rename_semestrinfo_semesterinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttoteacher',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Предмет преподаётся в данный момент'),
        ),
    ]
