# Generated by Django 4.2.1 on 2023-06-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_subjecttoteacher_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('FP', '2 ПЗ'), ('FT', '2 ТЗ'), ('HP', '1 ПЗ'), ('HT', '1 ТЗ'), ('FF', '1 ТЗ, 1 ПЗ')], default='FF', max_length=2, null=True, verbose_name='Тип занятия'),
        ),
        migrations.AlterField(
            model_name='studenttogroup',
            name='zachotka',
            field=models.CharField(db_index=True, max_length=20, null=True, unique=True, verbose_name='Номер зачётки'),
        ),
        migrations.AlterField(
            model_name='subjecttoteacher',
            name='hours',
            field=models.PositiveIntegerField(default=1, verbose_name='Часы'),
        ),
    ]
