# Generated by Django 4.2.1 on 2023-06-17 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_alter_lesson_type_alter_studenttogroup_zachotka_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предметы', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RemoveField(
            model_name='groups',
            name='course',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='semesterinfo',
            name='start_date',
        ),
        migrations.AddField(
            model_name='groups',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.semesterinfo', verbose_name='Текущий семестр'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='start_year',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата зачисления группы'),
        ),
        migrations.AlterField(
            model_name='semesterinfo',
            name='weeks',
            field=models.PositiveIntegerField(default=17, verbose_name='Количество недель'),
        ),
        migrations.AlterField(
            model_name='subjecttoteacher',
            name='teacher',
            field=models.ForeignKey(limit_choices_to=models.Q(('role', 'TE'), ('role', 'AD'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
    ]
