# Generated by Django 4.2.1 on 2023-06-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_alter_subject_options_remove_groups_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciality',
            old_name='mounths',
            new_name='months',
        ),
        migrations.RemoveField(
            model_name='subjecttoteacher',
            name='semester',
        ),
        migrations.AddField(
            model_name='subjecttoteacher',
            name='yearhalf',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='Полугодие'),
        ),
        migrations.AlterField(
            model_name='subjecttoteacher',
            name='course',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='Курс'),
        ),
    ]
