# Generated by Django 4.2.1 on 2023-06-18 20:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_rename_mounths_speciality_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterinfo',
            name='rubej',
            field=models.DateField(default=datetime.datetime(2023, 6, 18, 20, 7, 23, 888101, tzinfo=datetime.timezone.utc), verbose_name='Дата рубежа'),
        ),
        migrations.AddField(
            model_name='semesterinfo',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2023, 6, 18, 20, 7, 23, 888101, tzinfo=datetime.timezone.utc), verbose_name='Дата начало семестра'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.semesterinfo', verbose_name='Текущий семестр'),
        ),
    ]
