# Generated by Django 4.2.1 on 2023-06-18 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_semesterinfo_rubej_semesterinfo_startdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semesterinfo',
            old_name='semester',
            new_name='yearhalf',
        ),
        migrations.AlterField(
            model_name='semesterinfo',
            name='rubej',
            field=models.DateField(default=datetime.datetime(2023, 6, 18, 20, 8, 35, 183781, tzinfo=datetime.timezone.utc), verbose_name='Дата рубежа'),
        ),
        migrations.AlterField(
            model_name='semesterinfo',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2023, 6, 18, 20, 8, 35, 183781, tzinfo=datetime.timezone.utc), verbose_name='Дата начало семестра'),
        ),
    ]
